version: "3"
services:
  cash-register:
    restart: always
    build: .
    ports:
      - "14321:3000"
    volumes:
      - /Users/julianteh/OneDrive/Chillian/Cash-Register/data:/app/data
    env_file: /Users/julianteh/OneDrive/Chillian/Cash-Register/data/cash-register.env